from os import getenv

REDIS_DEFAULT = "0"
REDIS_TRAFFIC = "1"
REDIS_T = "2"

REDIS_HOST = getenv("REDIS_HOST","localhost")
REDIS_PORT = getenv("REDIS_HOST",6379)

POSTGRES_HOST = getenv("REDIS_HOST","localhost")
POSTGRES_HOST = getenv("REDIS_HOST",5432)
POSTGRES_DB = getenv("POSTGRES_DB","postgres")
POSTGRES_USERNAME = getenv("POSTGRES_USERNAME","postgres")
POSTGRES_PASSWORD = getenv("POSTGRES_PASSWORD","postgres")

RABBITMQ_HOST = getenv("RABBITMQ_HOST", "5.75.188.0")
RABBITMQ_PORT = getenv("RABBITMQ_PORT", "5672")
RABBITMQ_VIRTUAL_HOST = getenv("RABBITMQ_VIRTUAL_HOST", "/")
RABBITMQ_EXCHANGE = getenv("RABBITMQ_EXCHANGE", "master")
RABBITMQ_QUEUE = getenv("RABBITMQ_QUEUE", "master")
USAGE_ROUTING_KEY = getenv("USAGE_ROUTING_KEY", "usage")
RABBITMQ_USERNAME = getenv("RABBITMQ_USERNAME", "slave")
RABBITMQ_PASSWORD = getenv("RABBITMQ_PASSWORD", "eN6um5s7ZfQegYx")

V2RAY_CONFIG_PATH = getenv("V2RAY_CONFIG_PATH","/root/v2/config-main.json")
CLOUDFLARE_IP = getenv("CLOUDFLARE_IP","104.18.125.0")
ARVAN_DOMAIN = getenv("CLOUDFLARE_DOMAIN","wearejadi.vpnmaster.uno")
TELEGRAM_BOT_TOKEN = getenv("TELEGRAM_BOT_TOKEN","5705397533:AAGnWZCHdqNFv_nhgNCYyVMXBLaMNx6S")
