from os import getenv

REDIS_DEFAULT = 0
REDIS_TRAFFIC = 1
REDIS_CELERY_BROKER = 2
REDIS_CELERY_BACKEND = 3

REDIS_HOST = getenv("REDIS_HOST", "localhost")
REDIS_PORT = getenv("REDIS_PORT", 6379)

RABBITMQ_HOST = getenv("RABBITMQ_HOST", "5.75.188.0")
RABBITMQ_PORT = getenv("RABBITMQ_PORT", "5672")
RABBITMQ_VIRTUAL_HOST = getenv("RABBITMQ_VIRTUAL_HOST", "/")
RABBITMQ_EXCHANGE = getenv("RABBITMQ_EXCHANGE", "master")
RABBITMQ_QUEUE = getenv("RABBITMQ_QUEUE", "slave")
USAGE_ROUTING_KEY = getenv("USAGE_ROUTING_KEY", "usage")
RABBITMQ_USERNAME = getenv("RABBITMQ_USERNAME", "slave")
RABBITMQ_PASSWORD = getenv("RABBITMQ_PASSWORD", "eN6um5s7ZfQegYx")

V2RAY_HOST = getenv("V2RAY_HOST","127.0.0.1")
V2RAY_PORT = getenv("V2RAY_PORT",80)

SENTRY_DSN_ADDRESS = getenv(
    "SENTRY_DSN_ADDRESS", "http://e7ff4e71994848e595e83d457af2579a@localhost:9000/2"
)

V2RAY_CONFIG_PATH = getenv("V2RAY_CONFIG_PATH", "/root/v2/config-main.json")
CLOUDFLARE_IP = getenv("CLOUDFLARE_IP", "104.18.125.0")
ARVAN_DOMAIN = getenv("CLOUDFLARE_DOMAIN", "wearejadi.vpnmaster.uno")
TELEGRAM_BOT_TOKEN = getenv(
    "TELEGRAM_BOT_TOKEN", "5705397533:AAGnWZCHdqNFv_nhgNCYyVMXBLaMNx6S"
)
