version: '3.3'

services:
  redis-slave:
    container_name: redis-slave
    restart: always
    image: redis:6.2.7
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - redis-slave-data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - slave-network

volumes:
  redis-slave-data:
    external: True

networks:
  slave-network:
    external: True
